CREATE TABLE "D5000"."YK_HIS_CONTENT"
(
"OCCUR_TIME" DATETIME(6) NOT NULL,
"YX_ID" NUMBER(22,0) NOT NULL,
"TERM_ID" NUMBER(22,0),
"CONTENT" VARCHAR2(512) NOT NULL,
"YKRESULT" VARCHAR2(256),
"BAK_1" VARCHAR2(128),
"BAK_2" NUMERIC(26,6),
"BAK_3" VARCHAR2(50),
"TERM_AREA_ID" NUMERIC(26,0),
"IF_STAT_STATIC" VARCHAR2(10),
"IF_ZF_GW" VARCHAR2(10),
"IF_YY_ZB" VARCHAR2(50),
NOT CLUSTER PRIMARY KEY("OCCUR_TIME", "YX_ID", "CONTENT")) STORAGE(ON "OPEN_DATA", CLUSTERBTR) ;
COMMENT ON TABLE "D5000"."YK_HIS_CONTENT" IS '遥控明细历史表';
COMMENT ON COLUMN "D5000"."YK_HIS_CONTENT"."BAK_1" IS '备用1';
COMMENT ON COLUMN "D5000"."YK_HIS_CONTENT"."BAK_2" IS '备用2';
COMMENT ON COLUMN "D5000"."YK_HIS_CONTENT"."BAK_3" IS '备用3';
COMMENT ON COLUMN "D5000"."YK_HIS_CONTENT"."CONTENT" IS '明细';
COMMENT ON COLUMN "D5000"."YK_HIS_CONTENT"."OCCUR_TIME" IS '发生时间';
COMMENT ON COLUMN "D5000"."YK_HIS_CONTENT"."TERM_ID" IS '终端ID';
COMMENT ON COLUMN "D5000"."YK_HIS_CONTENT"."YKRESULT" IS '结果';
COMMENT ON COLUMN "D5000"."YK_HIS_CONTENT"."YX_ID" IS '遥信ID';
