CREATE TABLE "D5000"."YK_SUCCESS_CONTENT"
(
"OCCUR_TIME" DATETIME(6) NOT NULL,
"MEAS_ID" NUMBER(22,0) NOT NULL,
"TERM_ID" NUMBER(22,0),
"CONTENT" VARCHAR2(512) NOT NULL,
"YKRESULT" VARCHAR2(256),
"BAK_1" VARCHAR2(128),
"BAK_2" NUMERIC(26,6),
"BAK_3" VARCHAR2(50),
"TERM_AREA_ID" NUMERIC(26,0),
"IF_STAT_STATIC" VARCHAR2(10),
"IF_ZF_GW" VARCHAR2(10),
NOT CLUSTER PRIMARY KEY("OCCUR_TIME", "MEAS_ID", "CONTENT")) STORAGE(ON "OPEN_DATA", CLUSTERBTR) ;